---
- name: install dci-agent
  yum:
    name: https://packages.distributed-ci.io/dci-release.el7.noarch.rpm
    state: present
  become: yes

- name: install dci-ansible
  yum:
    name: dci-ansible
    state: present
  become: yes

- name: Add centos user to dci group
  user:
    name: centos
    groups: dci
    append: yes
  become: yes
